# Generated by Django 5.0.6 on 2026-07-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudmodel',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudmodel',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
