# Generated by Django 5.0.6 on 2026-06-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripcion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='descripcion_corta',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planmodel',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
