# Generated by Django 5.0.6 on 2026-06-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresamodel',
            name='logo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
