# Generated by Django 5.0.6 on 2026-07-01 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('empresa', '0002_alter_empresamodel_logo_url'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('tolerancia_ingreso_min', models.PositiveIntegerField(default=15)),
                ('tolerancia_salida_min', models.PositiveIntegerField(default=0)),
                ('horas_extras_permitidas', models.BooleanField(default=False)),
                ('max_horas_extras_dia', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='empresa.empresamodel')),
            ],
            options={
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='AsignacionHorarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuario.usuariomodel')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_horario', to='empleado.empleadomodel')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='horario.horariomodel')),
            ],
            options={
                'db_table': 'horarios_asignaciones',
            },
        ),
        migrations.CreateModel(
            name='TurnoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.SmallIntegerField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('minutos_refrigerio', models.PositiveIntegerField(default=0)),
                ('es_laborable', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='horario.horariomodel')),
            ],
            options={
                'db_table': 'horarios_turnos',
                'unique_together': {('horario', 'dia_semana')},
            },
        ),
    ]
