# Generated by Django 5.0.6 on 2026-07-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistenciamodel',
            name='es_manual',
        ),
        migrations.RemoveField(
            model_name='registroasistenciamodel',
            name='es_tardanza',
        ),
        migrations.RemoveField(
            model_name='registroasistenciamodel',
            name='justificacion_manual',
        ),
        migrations.RemoveField(
            model_name='registroasistenciamodel',
            name='metodo',
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='estado_auditoria',
            field=models.CharField(choices=[('VALIDO', 'Válido'), ('CORREGIDO', 'Corregido'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_APROBACION', 'Pendiente de aprobación')], default='VALIDO', max_length=25),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='minutos_extra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='minutos_tardanza',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='minutos_temprano',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='nivel_confianza',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='origen',
            field=models.CharField(choices=[('WEB', 'Web'), ('QR', 'Código QR'), ('MOVIL', 'App Móvil'), ('MANUAL', 'Registro manual'), ('API', 'Sistema/API')], default='WEB', max_length=15),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='resultado',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('TARDE', 'Tarde'), ('TEMPRANO', 'Temprano'), ('EXTRA', 'Extra'), ('FALTA', 'Falta'), ('FUERA_HORARIO', 'Fuera de horario')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='tokenqrmodel',
            name='firma',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='tokenqrmodel',
            name='nonce',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='registroasistenciamodel',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('INICIO_REFRIGERIO', 'Inicio de refrigerio'), ('FIN_REFRIGERIO', 'Fin de refrigerio'), ('SALIDA', 'Salida')], max_length=20),
        ),
        migrations.AlterField(
            model_name='tokenqrmodel',
            name='token',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
