# Generated by Django 5.0.6 on 2026-07-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_remove_registroasistenciamodel_es_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='enviado_a_nomina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='estado_extras',
            field=models.CharField(choices=[('NO_REQUIERE', 'No requiere'), ('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='NO_REQUIERE', max_length=20),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='extras_comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='extras_evaluado_por_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='extras_fecha_evaluacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistenciamodel',
            name='minutos_extra_aprobados',
            field=models.IntegerField(default=0),
        ),
    ]
