# Generated by Django 5.0.6 on 2026-07-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariomodel',
            name='estado_seguridad',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PASSWORD_CHANGE_REQUIRED', 'Cambio de contraseña requerido'), ('PASSWORD_EXPIRED', 'Contraseña expirada'), ('ACCOUNT_LOCKED', 'Cuenta bloqueada')], default='NORMAL', max_length=40),
        ),
        migrations.AddField(
            model_name='usuariomodel',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
